#!/usr/bin/env bash
# Merge per-actor dogfooding journal shards for a month.

set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "usage: tools/dogfooding/journal-cat.sh YYYY-MM" >&2
  exit 2
fi

MONTH="$1"
if [[ ! "$MONTH" =~ ^[0-9]{4}-[0-9]{2}$ ]]; then
  echo "journal-cat: month must match YYYY-MM (got '$MONTH')" >&2
  exit 2
fi

if TOPLEVEL="$(git rev-parse --show-toplevel 2>/dev/null)"; then
  cd "$TOPLEVEL"
fi

python3 - "$MONTH" <<'PY'
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone, timedelta
from pathlib import Path
import re
import sys

month = sys.argv[1]
journal_dir = Path("raw/internal/dogfooding")
paths = sorted(journal_dir.glob(f"mcp-interactions-journal-{month}*.md"))

if not paths:
    print(f"journal-cat: no journal shards found for {month}", file=sys.stderr)
    raise SystemExit(1)

header_re = re.compile(
    r"^###\s+"
    r"(?P<stamp>\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2})\s+"
    r"(?P<tz>[A-Z]{2,4})"
    r"(?:\s+(?:-|--|\u2014)|$)"
)
tz_offsets = {
    "PDT": timezone(timedelta(hours=-7)),
    "PST": timezone(timedelta(hours=-8)),
    "UTC": timezone.utc,
}


@dataclass(frozen=True)
class Entry:
    sort_dt: datetime
    actor: str
    source: str
    line: int
    text: str


def fail(path: Path, line: int, message: str) -> None:
    print(f"journal-cat: {path}:{line}: {message}", file=sys.stderr)
    raise SystemExit(1)


def actor_for(path: Path) -> str:
    stem = path.stem
    prefix = f"mcp-interactions-journal-{month}"
    if stem == prefix:
        return "shared"
    if stem.startswith(prefix + "-"):
        actor = stem[len(prefix) + 1 :]
        return actor or "shared"
    return stem


def parse_header(path: Path, line: int, text: str) -> datetime:
    match = header_re.match(text)
    if not match:
        fail(path, line, "entry header must start with '### YYYY-MM-DD HH:MM TZ'")
    tz_name = match.group("tz")
    tz = tz_offsets.get(tz_name)
    if tz is None:
        fail(path, line, f"unsupported timezone {tz_name!r}")
    local_dt = datetime.strptime(match.group("stamp"), "%Y-%m-%d %H:%M").replace(tzinfo=tz)
    return local_dt.astimezone(timezone.utc)


def parse_file(path: Path) -> list[Entry]:
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    try:
        interactions_idx = next(i for i, line in enumerate(lines) if line.rstrip("\n") == "## Interactions")
    except StopIteration:
        fail(path, 1, "missing '## Interactions' marker")

    entries: list[Entry] = []
    actor = actor_for(path)
    i = interactions_idx + 1
    while i < len(lines):
        while i < len(lines) and not lines[i].strip():
            i += 1
        if i >= len(lines):
            break
        line_no = i + 1
        if not lines[i].startswith("### "):
            fail(path, line_no, "non-preamble content after '## Interactions' is not an entry header")
        sort_dt = parse_header(path, line_no, lines[i].rstrip("\n"))
        j = i + 1
        while j < len(lines) and not lines[j].startswith("### "):
            j += 1
        entries.append(
            Entry(
                sort_dt=sort_dt,
                actor=actor,
                source=str(path),
                line=line_no,
                text="".join(lines[i:j]),
            )
        )
        i = j
    return entries


entries: list[Entry] = []
for path in paths:
    entries.extend(parse_file(path))

entries.sort(key=lambda entry: (entry.sort_dt, entry.actor, entry.source, entry.line))

print(f"# ECHO MCP interactions journal - {month} merged shards")
print()
print(
    "Generated by tools/dogfooding/journal-cat.sh from "
    f"raw/internal/dogfooding/mcp-interactions-journal-{month}*.md."
)
print("The merged stream includes per-actor shards and the frozen legacy shared file when present.")
print()
print(
    "**Timezone convention:** entries are written in founder local time "
    "(PDT/PST, America/Los_Angeles) unless explicitly noted."
)
print()
print("## Quick-Fill Template")
print()
print("    ### YYYY-MM-DD HH:MM PDT - <one-line context>")
print()
print("    - **Trigger:** <why the tool was called>")
print("    - **Query inputs:** <tool(args), one line or compact numbered list>")
print("    - **Returned:** <N clusters/M atoms, N matches, N turns, warnings, top label/rank reasons>")
print("    - **Sources:** <source_breakdown | source_resolved | per-match prefixes | exact paths>")
print("    - **Verdict:** <right | partial | wrong> - <short reason>")
print("    - **Note:** <what felt useful/off>")
print("    - **Conjecture:** <optional>")
print()
print("## Interactions")

for entry in entries:
    print()
    sys.stdout.write(entry.text)
    if not entry.text.endswith("\n"):
        print()
PY
