#!/usr/bin/env python3
"""Emit a validated review-pending sidecar from a structured descriptor."""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import uuid
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _lib  # noqa: E402
import _sidecar_validate  # noqa: E402

ITEM_ID_RE = re.compile(r"^\d{4}-\d{2}-\d{2}-\d{3}[a-z]?-[a-z][a-z0-9-]*$")
ALLOWED_DESCRIPTOR_KEYS = {"item_id", "verdict", "test_counts", "body", "producer", "reviewed_at"}
REQUIRED_BODY_KEYS = {"verdict", "pre_merge_fixups", "expected_merge_conflicts", "followups"}


def _die(message: str) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(1)


def _load_descriptor(path: str | None) -> dict[str, Any]:
    try:
        if path is None or path == "-":
            raw = sys.stdin.read()
        else:
            raw = Path(path).read_text(encoding="utf-8")
        data = json.loads(raw)
    except OSError as exc:
        _die(f"failed to read descriptor: {exc}")
    except json.JSONDecodeError as exc:
        _die(f"invalid JSON descriptor: {exc}")
    if not isinstance(data, dict):
        _die("descriptor must be a JSON object")
    return data


def _repo_root() -> Path:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            check=True,
            capture_output=True,
            text=True,
        )
    except subprocess.CalledProcessError as exc:
        detail = (exc.stderr or exc.stdout or str(exc)).strip()
        _die(f"failed to resolve git repo root: {detail}")
    return Path(out.stdout.strip())


def _require_string(mapping: dict[str, Any], key: str, where: str) -> str:
    value = mapping.get(key)
    if not isinstance(value, str):
        _die(f"{where}.{key} must be a string")
    return value


def _validate_descriptor(data: dict[str, Any]) -> tuple[str, dict[str, Any], str]:
    unknown = sorted(set(data) - ALLOWED_DESCRIPTOR_KEYS)
    if unknown:
        _die(f"unknown descriptor field(s): {', '.join(unknown)}")

    for key in ("item_id", "verdict", "test_counts", "body"):
        if key not in data:
            _die(f"missing required descriptor field: {key}")

    item_id = _require_string(data, "item_id", "descriptor")
    if not ITEM_ID_RE.match(item_id):
        _die(f"item_id does not match review sidecar pattern: {item_id}")

    supplied_producer = data.get("producer")
    if supplied_producer is not None and supplied_producer != _sidecar_validate.PRODUCER:
        _die("producer is generated by emit-sidecar.py and must not conflict")
    if "reviewed_at" in data:
        _die("reviewed_at is generated by emit-sidecar.py and must not be supplied")

    body_data = data["body"]
    if not isinstance(body_data, dict):
        _die("descriptor.body must be an object")

    verdict = _require_string(data, "verdict", "descriptor")
    body_unknown = sorted(set(body_data) - (REQUIRED_BODY_KEYS | {"open_questions"}))
    if body_unknown:
        _die(f"unknown descriptor.body field(s): {', '.join(body_unknown)}")
    for key in sorted(REQUIRED_BODY_KEYS):
        if key not in body_data:
            _die(f"missing required descriptor.body field: {key}")
    if verdict == "block":
        if "open_questions" not in body_data:
            _die("descriptor.body.open_questions is required when verdict is block")
    elif "open_questions" in body_data:
        _die("descriptor.body.open_questions is only allowed when verdict is block")

    fm = {
        "item_id": item_id,
        "verdict": verdict,
        "reviewed_at": _lib.iso_utc_now(),
        "test_counts": data["test_counts"],
        "producer": _sidecar_validate.PRODUCER,
    }
    body = _render_body(body_data, verdict)
    return item_id, fm, body


def _section(heading: str, content: str) -> str:
    return f"## {heading}\n{content.rstrip()}\n"


def _render_body(body_data: dict[str, Any], verdict: str) -> str:
    rendered = [
        _section("Verdict", _require_string(body_data, "verdict", "descriptor.body")),
        _section("Pre-merge fixups", _require_string(body_data, "pre_merge_fixups", "descriptor.body")),
        _section(
            "Expected merge conflicts",
            _require_string(body_data, "expected_merge_conflicts", "descriptor.body"),
        ),
        _section(
            "Follow-up items (defer, do not block merge)",
            _require_string(body_data, "followups", "descriptor.body"),
        ),
    ]
    if verdict == "block":
        rendered.append(
            _section(
                "Open questions for founder",
                _require_string(body_data, "open_questions", "descriptor.body"),
            )
        )
    return "\n".join(rendered)


def _finalize(target: Path, content: str, replace: bool) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_name(f"{target.name}.{uuid.uuid4().hex}.tmp")
    try:
        tmp.write_text(content, encoding="utf-8")
        try:
            tmp_fm, tmp_body = _lib.parse_frontmatter(tmp)
        except ValueError as exc:
            tmp.unlink()
            _die(f"assembled temp sidecar is malformed: {exc}")
        error = _sidecar_validate.validate(tmp_fm, tmp_body)
        if error is not None:
            tmp.unlink()
            _die(f"assembled temp sidecar failed validation: {error}")
        if replace:
            os.replace(tmp, target)
        else:
            os.link(tmp, target)
            tmp.unlink()
    except FileExistsError:
        if tmp.exists():
            tmp.unlink()
        _die(f"target already exists: {target}")
    except Exception:
        if tmp.exists():
            tmp.unlink()
        raise


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", help="JSON descriptor path; defaults to stdin")
    parser.add_argument("--replace", action="store_true", help="atomically replace an existing sidecar")
    args = parser.parse_args(argv[1:])

    data = _load_descriptor(args.input)
    item_id, fm, body = _validate_descriptor(data)
    error = _sidecar_validate.validate(fm, body)
    if error is not None:
        _die(f"assembled sidecar failed validation: {error}")

    target = _repo_root() / "backlog" / "pending_review" / f"{item_id}.review.md"
    _finalize(target, _lib.serialize_frontmatter(fm, body), args.replace)
    print(target)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
