// Validation harness for item 020 — open-loop resolution heuristics (R1).
//
// Calls get_recent_work_context over a 7-day window against live storage
// and writes a per-hint scoring sheet to
// raw/internal/dogfooding/020-resolution-validation.md. The founder
// hand-scores each row (TP / FP / TN / FN); this script does NOT auto-score.
//
// Usage:
//   npx vite-node tools/validate-resolution.ts
//   npx vite-node tools/validate-resolution.ts --days 14
//   npx vite-node tools/validate-resolution.ts --out /tmp/score.md
//
// Storage path resolution mirrors the daemon (src/daemon/index.ts):
//   ECHO_DB_PATH > ECHO_DATA_DIR/echo.db > ~/Library/Application Support/ECHO/echo.db

import { mkdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';

import { getRecentWorkContext } from '../src/mcp/tools/recent-work-context.js';
import { SqliteStorage } from '../src/storage/sqlite.js';
import type { OpenLoopHintEnriched } from '../src/trace/types.js';
import type { NormalizedContextEvent } from '../src/normalize/types.js';

interface Args {
  days: number;
  outPath: string;
}

function parseArgs(argv: string[]): Args {
  const args: Args = {
    days: 7,
    outPath: defaultOutPath(),
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--days') {
      const v = argv[++i];
      if (v !== undefined) args.days = Math.max(1, Number.parseInt(v, 10));
    } else if (a === '--out') {
      const v = argv[++i];
      if (v !== undefined) args.outPath = resolve(v);
    }
  }
  return args;
}

function defaultOutPath(): string {
  const repo = resolve(import.meta.dirname, '..');
  return join(
    repo,
    'raw',
    'internal',
    'dogfooding',
    '020-resolution-validation.md',
  );
}

function resolveDbPath(): string {
  const dbPath = process.env['ECHO_DB_PATH'];
  if (dbPath !== undefined && dbPath.length > 0) return resolve(dbPath);
  const dataDir = process.env['ECHO_DATA_DIR'];
  if (dataDir !== undefined && dataDir.length > 0) {
    return join(resolve(dataDir), 'echo.db');
  }
  return join(homedir(), 'Library', 'Application Support', 'ECHO', 'echo.db');
}

function escapeCell(s: string | undefined): string {
  if (s === undefined) return '';
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ⏎ ').slice(0, 240);
}

interface Row {
  kind: OpenLoopHintEnriched['kind'];
  text: string;
  resolved: boolean;
  resolved_by_atom_id: string | undefined;
  hint_atom_id: string;
  hint_atom_url: string;
  hint_atom_time: string;
  resolved_by_atom_time: string | undefined;
}

function buildRow(
  hint: OpenLoopHintEnriched,
  atoms: Record<string, NormalizedContextEvent>,
): Row {
  const hintAtom = atoms[hint.atom_id];
  const resolverAtom =
    hint.resolved_by_atom_id !== undefined
      ? atoms[hint.resolved_by_atom_id]
      : undefined;
  const row: Row = {
    kind: hint.kind,
    text: hint.text,
    resolved: hint.resolved,
    resolved_by_atom_id: hint.resolved_by_atom_id,
    hint_atom_id: hint.atom_id,
    hint_atom_url: hintAtom?.source.raw_pointer ?? '',
    hint_atom_time: hintAtom?.time.occurred_at ?? '',
    resolved_by_atom_time: resolverAtom?.time.occurred_at,
  };
  return row;
}

function renderMarkdown(rows: Row[], days: number, until: string): string {
  const header = `# Open-loop resolution validation (item 020 R1)

Generated by \`tools/validate-resolution.ts\` over the last ${days} days
of live ECHO storage (window ending ${until}).

The founder hand-scores each row in the **Verdict** column:
- **TP** — \`resolved: true\` and the loop is actually closed.
- **FP** — \`resolved: true\` but the loop is actually still open.
- **TN** — \`resolved: false\` and the loop is actually still open.
- **FN** — \`resolved: false\` but the loop is actually closed.

Aggregate after scoring: \`precision = TP / (TP + FP)\`. Per-rule breakdown
helps surface which kind drives precision loss.

Total rows: ${rows.length} (${rows.filter((r) => r.resolved).length} resolved, ${rows.filter((r) => !r.resolved).length} unresolved)

| # | Kind | Resolved | Hint atom (id · time · raw_pointer) | Resolved-by (id · time) | Hint text | Verdict |
|---|---|---|---|---|---|---|
`;
  const body = rows
    .map((r, i) => {
      const hintAtomCell = `\`${r.hint_atom_id}\` · ${r.hint_atom_time} · \`${escapeCell(r.hint_atom_url)}\``;
      const resolverCell =
        r.resolved_by_atom_id !== undefined
          ? `\`${r.resolved_by_atom_id}\` · ${r.resolved_by_atom_time ?? ''}`
          : '';
      return `| ${i + 1} | ${r.kind} | ${r.resolved ? '✅' : '❌'} | ${escapeCell(
        hintAtomCell,
      )} | ${escapeCell(resolverCell)} | ${escapeCell(r.text)} |  |`;
    })
    .join('\n');

  const breakdown = (() => {
    const counts: Record<string, { total: number; resolved: number }> = {};
    for (const r of rows) {
      const c = counts[r.kind] ?? { total: 0, resolved: 0 };
      c.total += 1;
      if (r.resolved) c.resolved += 1;
      counts[r.kind] = c;
    }
    const lines = Object.entries(counts)
      .sort()
      .map(
        ([k, v]) =>
          `- **${k}** — ${v.total} hints (${v.resolved} resolved, ${v.total - v.resolved} unresolved)`,
      );
    return `\n\n## Per-rule breakdown\n\n${lines.join('\n')}\n`;
  })();

  return `${header}${body}\n${breakdown}\n`;
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  const dbPath = resolveDbPath();
  console.log(`ECHO validate-resolution`);
  console.log(`  db:      ${dbPath}`);
  console.log(`  window:  last ${args.days}d`);
  console.log(`  output:  ${args.outPath}`);

  const storage = new SqliteStorage(dbPath);
  try {
    const now = new Date();
    const until = now.toISOString();
    const since = new Date(
      now.getTime() - args.days * 24 * 3600 * 1000,
    ).toISOString();

    const response = await getRecentWorkContext(
      storage,
      { since, until, limit: 500 },
      now,
    );

    const rows: Row[] = [];
    for (const cluster of response.clusters) {
      for (const hint of cluster.open_loop_hints) {
        rows.push(buildRow(hint, response.atoms));
      }
    }

    const md = renderMarkdown(rows, args.days, until);
    mkdirSync(dirname(args.outPath), { recursive: true });
    writeFileSync(args.outPath, md, 'utf-8');

    console.log(
      `\nwrote ${rows.length} rows (${rows.filter((r) => r.resolved).length} resolved) to ${args.outPath}`,
    );
  } finally {
    storage.close();
  }
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
